("name" . "Xyzzy Multiframe Version")
("author" . "mumurik765")
("url" . "https://raw.github.com/mumurik/xyzzy/tree/ni-integrate/latest-xyzzy-info.l")
("description" . "Xyzzyのマルチフレーム版配布サイトです。")
("packages"
 (("name" . "xyzzy") ("version" . "0.2.3.8.1") ("author" . "mumurik765") ("file" . "multiframe_0_2_3_8.zip") ("src" . "https://bitbucket.org/mumurik/xyzzy/downloads/multiframe_0_2_3_8.zip") ("description" . "0.2.3.8") ("category") ("md5" . "88b3f390ba93d9ad9fb2ece719ae158f") ("time" . 3545469788) ("depends") ("changes" . "0.2.3.8 release version.") ("notice" . "") ("load-after-install" . "") ("load-before-uninstall" . ""))
 )
