("name" . "Xyzzy Multiframe Version")
("author" . "mumurik765")
("url" . "https://raw.github.com/mumurik/xyzzy/tree/ni-integrate/latest-xyzzy-info.l")
("description" . "Xyzzyのマルチフレーム版配布サイトです。")
("packages"
 (("name" . "xyzzy") ("version" . "0.2.3.9.0") ("author" . "mumurik765") ("file" . "multiframe_0_2_3_9_alpha1.zip") ("src" . "https://bitbucket.org/mumurik/xyzzy/downloads/multiframe_0_2_3_9_alpha1.zip") ("description" . "0.2.3.9 alpha version.") ("category") ("md5" . "ed119a18e5360721325a917ba386e26a") ("time" . 3546928255) ("depends") ("changes" . "0.2.3.9 alpha version.") ("notice" . "") ("load-after-install" . "") ("load-before-uninstall" . ""))
 )
