("name" . "Xyzzy Multiframe Version")
("author" . "mumurik765")
("url" . "https://raw.github.com/mumurik/xyzzy/tree/ni-integrate/latest-xyzzy-info.l")
("description" . "Xyzzyのマルチフレーム版配布サイトです。")
("packages"
 (("name" . "xyzzy") ("version" . "0.2.3.7.6") ("author" . "mumurik765") ("file" . "multiframe_0_2_3_7.zip") ("src" . "https://bitbucket.org/mumurik/xyzzy/downloads/multiframe_0_2_3_7.zip") ("description" . "0.2.3.7 Release.") ("category") ("md5" . "00ff318c68a930454638540689b76b83") ("time" . 3542755994) ("depends") ("changes" . "0.2.3.7 Release version.") ("notice" . "") ("load-after-install" . "") ("load-before-uninstall" . ""))
 )
