("name" . "Xyzzy Multiframe Version")
("author" . "mumurik765")
("url" . "https://raw.github.com/mumurik/xyzzy/tree/ni-integrate/latest-xyzzy-info.l")
("description" . "Xyzzyのマルチフレーム版配布サイトです。")
("packages"
 (("name" . "xyzzy") ("version" . "0.2.3.8.0") ("author" . "mumurik765") ("file" . "multiframe_0_2_3_8_alpha.zip") ("src" . "https://bitbucket.org/mumurik/xyzzy/downloads/multiframe_0_2_3_8_alpha.zip") ("description" . "0.2.3.8 alpha") ("category") ("md5" . "0d4b31bd94edb2290da45a1fdcb9df9e") ("time" . 3545221329) ("depends") ("changes" . "0.2.3.8 alpha version.") ("notice" . "") ("load-after-install" . "") ("load-before-uninstall" . ""))
 )
